import random
from time import sleep


def login():
    tries = 0
    while tries < 3:
        print("Login to play Guess the Number!")
        username = str(input("Please enter your username: "))
        password = str(input("Please enter your password: "))
        if username == ("chetan") and password == ("1234"):
            print("Correct data..fetching your required game...")
            return True
        else:
            print("Incorrect password, please try again. ")
            tries = tries + 1
    print("Incorrect password entered 3 times, system self destroying... ")
    sleep(3)
    return False


def start_game():
    print("Hello and welcome to Guess the Number where you have to guess the number which is generated by a computer.")
    if login():

        number = random.randint(1,20)
        chances = 0

        print("Guess the Number between 0 and 20.")
        while chances < 100:
            guess = int(input())
            if guess == number:
                chances = chances + 1
                print(f"The number you've guessed was:{guess} and congratulations because you guessed the correct number in {chances} chances!")
                break

            elif guess < number:
                print("The number you provided was too low, try a higher number!")


            else:
                print("The number you provided was too high, try a lower number! ")


        if not chances < 100:
            print("Sorry, you lost and you have no tries left, please try again next time.")


start_game()